### ISSUE TITLE
Need a way to manually clear the caches

### ISSUE THREAD

**Issue by erichelgeson** [GR8conf/website#21]
And probably expire them a bit more often too.

**Comment by rpalcolea** [comment]
I guess expire them more often is the simplest approach using `timeToLiveSeconds` in the config.

Clearing the caches manually is a simple task to implement by invoking `grailsCacheAdminService`. However, this requires a security layer to prevent anyone from clearing caches. This would require some work since this app does NOT have a security framework (which makes sense). Is this the real desire?

**Comment by erichelgeson** [comment]
Not much security is needed - maybe just a token that is set at runtime then can be validated on an endpoint. eg: `/cache/clear?token=setfromEnv`

**Comment by rpalcolea** [comment]
that's a good idea... so this token will be generated while starting the app? similar to what crash does by default?

**Comment by erichelgeson** [comment]
We rotate logs in cloudwatch every 7 days so by the time we'd need to clear a cache it'd be gone. I think just reading in an environment variable is the best (since I can easily set that in beanstalk)

**Comment by rpalcolea** [comment]
This shoudl do it https://github.com/GR8conf/website/pull/23
